### ISSUE TITLE
news bot and calc bot both use 3 packages

### ISSUE THREAD

**Issue by Ediacarium** [Vinpasso/BridgeMPP-Bot#15]
IMO both bots should only use 1 package per bot as it clutters up the Packages list of IDEs (at least the package explorer from eclipse) if you have the following package list:

bots.CalcBot
bots.CalcBot.calc
bots.CalcBot.logger
bots.NewsBot
bots.NewsBot.logger
bots.NewsBot.news
bots.ParrotBot
bots.WikiHelpBot

**Comment by Vinpasso** [comment]
Reason: Inactive
